// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalApp.Data;

#nullable disable

namespace RentalApp.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20260909022211_TenantUnitIdAssignmentFix")]
    partial class TenantUnitIdAssignmentFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RentalApp.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UnitId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceDate");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("LeaseId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DueDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SecurityDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Status");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("UnitId", "Status");

                    b.ToTable("Leases", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("PropertyId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("UtilityAuditLogs", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedFromReadingId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecalculated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PreviousReading")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("RecalculationBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CreatedFromReadingId");

                    b.HasIndex("DueDate");

                    b.HasIndex("RecalculationBatchId");

                    b.HasIndex("Status");

                    b.HasIndex("UtilityTypeId");

                    b.HasIndex("UtilityCustomerId", "UtilityTypeId", "BillingPeriod")
                        .IsUnique();

                    b.ToTable("UtilityBills", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityBills_Amount_NonNegative", "Amount >= 0");

                            t.HasCheckConstraint("CK_UtilityBills_BillingPeriod_Length", "length(BillingPeriod) = 7");

                            t.HasCheckConstraint("CK_UtilityBills_Consumption_NonNegative", "Consumption >= 0");

                            t.HasCheckConstraint("CK_UtilityBills_Rate_NonNegative", "Rate >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityBillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("UtilityBillId");

                    b.ToTable("UtilityBillPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityBillPayments_Amount_Positive", "Amount > 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillResponsibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysCovered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageShare")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityBillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UtilityBillId", "TenantId", "FromDate", "ToDate")
                        .IsUnique();

                    b.ToTable("UtilityBillResponsibilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityBillResponsibilities_AmountShare_NonNegative", "AmountShare >= 0");

                            t.HasCheckConstraint("CK_UtilityBillResponsibilities_DaysCovered_NonNegative", "DaysCovered >= 0");

                            t.HasCheckConstraint("CK_UtilityBillResponsibilities_Percentage_NonNegative", "PercentageShare >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillingPeriodLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilityCustomerId");

                    b.HasIndex("UtilityTypeId", "UtilityCustomerId", "BillingPeriod")
                        .IsUnique();

                    b.ToTable("UtilityBillingPeriodLocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityBillingPeriodLocks_BillingPeriod_Length", "length(BillingPeriod) = 7");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DueDateRuleType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DueDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DueInDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UtilityCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerType");

                    b.HasIndex("Name");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UtilityCategoryId");

                    b.ToTable("UtilityCustomers", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityCustomers_DefaultRate_NonNegative", "DefaultRate IS NULL OR DefaultRate >= 0");

                            t.HasCheckConstraint("CK_UtilityCustomers_DueDay_Range", "DueDayOfMonth IS NULL OR (DueDayOfMonth >= 1 AND DueDayOfMonth <= 28)");

                            t.HasCheckConstraint("CK_UtilityCustomers_DueInDays_NonNegative", "DueInDays IS NULL OR DueInDays >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomerCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourcePaymentId");

                    b.HasIndex("UtilityTypeId");

                    b.HasIndex("UtilityCustomerId", "UtilityTypeId", "OccurredAt");

                    b.ToTable("UtilityCustomerCredits", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomerRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilityTypeId");

                    b.HasIndex("UtilityCustomerId", "UtilityTypeId", "BillingPeriod")
                        .IsUnique();

                    b.ToTable("UtilityCustomerRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityCustomerRates_BillingPeriod_Length", "length(BillingPeriod) = 7");

                            t.HasCheckConstraint("CK_UtilityCustomerRates_Rate_NonNegative", "Rate >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityMeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackdated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PreviousReadingValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("RecalculationBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecalculationBatchId");

                    b.HasIndex("UtilityTypeId");

                    b.HasIndex("UtilityCustomerId", "UtilityTypeId", "ReadingDate")
                        .IsUnique();

                    b.ToTable("UtilityMeterReadings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityMeterReadings_Consumption_NonNegative", "Consumption >= 0");

                            t.HasCheckConstraint("CK_UtilityMeterReadings_PreviousReading_NonNegative", "PreviousReadingValue >= 0");

                            t.HasCheckConstraint("CK_UtilityMeterReadings_Reading_NonNegative", "ReadingValue >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityRecalculationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerReadingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TriggerReadingId");

                    b.HasIndex("UtilityTypeId");

                    b.HasIndex("UtilityCustomerId", "UtilityTypeId", "StartedAt");

                    b.ToTable("UtilityRecalculationBatches", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UtilityTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityTypes_DefaultRate_NonNegative", "DefaultRate IS NULL OR DefaultRate >= 0");
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Expense", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Property", "Property")
                        .WithMany("Expenses")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Unit", "Unit")
                        .WithMany("Expenses")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Property");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Lease", "Lease")
                        .WithMany("Invoices")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lease");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Lease", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Room", "Room")
                        .WithMany("Leases")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Unit", "Unit")
                        .WithMany("Payments")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lease");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Room", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Unit", "Unit")
                        .WithMany("Rooms")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Unit", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBill", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityMeterReading", "CreatedFromReading")
                        .WithMany("UtilityBills")
                        .HasForeignKey("CreatedFromReadingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityRecalculationBatch", "RecalculationBatch")
                        .WithMany("RecalculatedBills")
                        .HasForeignKey("RecalculationBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany("Bills")
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany("Bills")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedFromReading");

                    b.Navigation("RecalculationBatch");

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillPayment", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityBill", "UtilityBill")
                        .WithMany("Payments")
                        .HasForeignKey("UtilityBillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillResponsibility", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityBill", "UtilityBill")
                        .WithMany("Responsibilities")
                        .HasForeignKey("UtilityBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillingPeriodLock", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany()
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany()
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomer", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityCategory")
                        .WithMany()
                        .HasForeignKey("UtilityCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Room");

                    b.Navigation("Tenant");

                    b.Navigation("UtilityCategory");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomerCredit", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityBillPayment", "SourcePayment")
                        .WithMany("Credits")
                        .HasForeignKey("SourcePaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany("Credits")
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany("CustomerCredits")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePayment");

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomerRate", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany("Rates")
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany("CustomerRates")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityMeterReading", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.UtilityRecalculationBatch", "RecalculationBatch")
                        .WithMany("RecalculatedReadings")
                        .HasForeignKey("RecalculationBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany("MeterReadings")
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany("MeterReadings")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecalculationBatch");

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityRecalculationBatch", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalApp.Domain.Entities.UtilityMeterReading", "TriggerReading")
                        .WithMany()
                        .HasForeignKey("TriggerReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityCustomer", "UtilityCustomer")
                        .WithMany()
                        .HasForeignKey("UtilityCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.UtilityType", "UtilityType")
                        .WithMany("RecalculationBatches")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("TriggerReading");

                    b.Navigation("UtilityCustomer");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Lease", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Property", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Room", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Leases");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Leases");

                    b.Navigation("Payments");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBill", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityBillPayment", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityCustomer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Credits");

                    b.Navigation("MeterReadings");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityMeterReading", b =>
                {
                    b.Navigation("UtilityBills");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityRecalculationBatch", b =>
                {
                    b.Navigation("RecalculatedBills");

                    b.Navigation("RecalculatedReadings");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UtilityType", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CustomerCredits");

                    b.Navigation("CustomerRates");

                    b.Navigation("MeterReadings");

                    b.Navigation("RecalculationBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
